### ISSUE TITLE
Async methods to post messages/actions in SDK 2.0.5 do not work

### ISSUE THREAD

**Issue by yujingwu** [artikcloud/artikcloud-java#1]
sendMessageAsync() does not work although sendMessage() work.
The same issue is for actions
The older version 2.0.3 works perfectly.

**Comment by jonathanpaek** [comment]
async calls found not working when debug mode is set true.   stream closes.
the following line can be removed for now until fix in place, or set to false.
client.setDebugging(true);

**Comment by yujingwu** [comment]
The tip provided above solved the problem. 

The root cause is at swagger. So close this issue.
