### ISSUE TITLE
No response data / response error feedback to user when working with Tasks / DeviceMangementApi

### ISSUE THREAD

**Issue by jonathanpaek** [artikcloud/artikcloud-java#3]
Error response body is being eaten up in SDK and only showing generic stack trace error to user.   No error response body is shown returned by API server.  

**Expected Error Sample - with response body**
```
{"error":{"code":4001,"id":"<redacted>","message":"Validation Error","errors":[[{"field":"property","message":["Missing path"]}]]}}
```

**Actual Error Sample - generic stack trace**
```
Exception in thread "main" cloud.artik.client.ApiException: Not Found
	at cloud.artik.client.ApiClient.handleResponse(ApiClient.java:1059)
```

Additionally after "successful" call - no way to retrieve successful response body 
```
TaskEnvelope taskEnvelope = devicesManagementApi.createTasks(taskRequest);
```

**Comment by yujingwu** [comment]
@jonathanpaek 

Thanks for reporting the issue. Please create internal engineering ticket for this. Otherwise, it is not visible to internal engineering team.

**Comment by wenboo** [comment]
@yujingwu  In the source code I see using "com.squareup.okhttp" && "com.google.gson", should I included the okhttp && gson jar file additionally ? thanks

**Comment by yujingwu** [comment]
@wenboo 
You do not need to include these jar files again if doing the following:

Here is what I would do with my java project. I do not build ARTIKCloud Java SDK jar from the source. Instead I use sdk jar file found in search.maven.org (search artikcloud). I can use one of the two ways to use sdk jar.
#1 download jar-with-dependencies.jar and link to it in the java project
#2 use maven instead. Then I do not need to download, instead add the dependency to artickloud-java in pom file of my java project, which will take care of download sdk jar and any depended jar files. Consult readme of this repository to learn how to add the dependency in your pom file.

**Comment by wenboo** [comment]
@yujingwu Thanks for sharing and I'd try the Maven java project as ReadMe.
